emp=input("enter the employee name")
id=input("enter the employee id")
dsg=input("enter the designation")
salary=input("enter the salary")
exp=input("experience")
add=input("enter the address")
place=input("enter the place")
pin=input("enter the pin code")
mob=input("enter the mobile number")
user=input("enter the user name")
password=input("enter the password")
password1=input("confirm password")
if(password==password1):
    print(emp)
    print(id)
    print(dsg)
    print(salary)
    print(exp)
    print(add)
    print(place)
    print(pin)
    print(mob)
    print(user)
    print(password)
    print(password1)
else:
    print("password and confirm password doesnt match")